[package]
name = "rust_generator"
version = "0.1.0"
edition = "2021"  # <-- Cambiado a 2021

# --- Añade esta sección completa ---
[lib]
crate-type = ["cdylib", "rlib"]
# ---------------------------------

[dependencies]
rxing = { version = "0.7.1", features = ["image", "svg_write"] }
base64 = "0.22.0"
image = "0.25.1"
wasm-bindgen = "0.2.92"