global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@codexproject.com'

# Configuración de enrutamiento de alertas
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning  
    receiver: 'warning-alerts'

# Receptores de alertas
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
    send_resolved: true

- name: 'critical-alerts'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/critical'
    send_resolved: true
    title: 'CRÍTICO: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      Alerta: {{ .Annotations.summary }}
      Descripción: {{ .Annotations.description }}
      Severidad: {{ .Labels.severity }}
      {{ end }}

- name: 'warning-alerts'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/warning'
    send_resolved: true
    title: 'ADVERTENCIA: {{ .GroupLabels.alertname }}'
    text: |
      {{ range .Alerts }}
      Alerta: {{ .Annotations.summary }}
      Descripción: {{ .Annotations.description }}
      {{ end }}

# Configuración de inhibición (evitar spam)
inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'dev', 'instance'] 