global:
  scrape_interval: 15s # Cada cuánto Prometheus recolecta métricas.

# Configuración de Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Reglas de alerta
rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'qreable-backend'
    # Asumiendo que tu backend Node.js corre en localhost:3001
    # y Prometheus corre con network_mode: host (O Docker Desktop en Mac/Win)
    static_configs:
      - targets: ['host.docker.internal:3004'] # Apuntar al puerto del servidor principal (3004) 